### ISSUE TITLE
Concat and minification?

### ISSUE THREAD

**Issue by zifnab87** [AntoineMary/grunt-angular-file-loader#1]
Since this is the most reliable angular source injector I have ever used.. is it too difficult to add concatenation and minification as well? There seems to be so much need for such a tool and https://github.com/claudio-silva/grunt-angular-builder doesn't cut it with external libraries.. Thank you so much!

**Comment by AntoineMary** [comment]
Hi, thanks for this comment !
The functions you ask for are planned this injector is far from the end but for the moment I'm really busy I can't work on it... The day I can improve it you will be the first to know !

**Comment by AntoineMary** [comment]
Afterthough, I will not implement functions to concat and minify in this plugin.
The main goal of it is to inject the files into the main HTML in the right order not more.

There is already a lot of grunt plugins thaht can concat and/or minify files easily, there is no need to write another one.

If you really want to concat / minify your files I can advise you to use this grunt plugins : 
https://www.npmjs.com/package/grunt-usemin
