### ISSUE TITLE
Add slash before the generated path

### ISSUE THREAD

**Issue by szabobar** [AntoineMary/grunt-angular-file-loader#3]
Dear developer!

Thanks for the plugin, it is very usefull for me, but I got a simple problem with it.

I would like to start all generated script src path from /
Because:
Current target is looks like: <script src="js/auth/auth.module.js" type="text/javascript"></script>
But If I write angular HTML5 url friendly application, and I got an application url like: http://localhost/login , then the generated scripts url would like to download from http://localhost/login/js/auth/... , and from the root. But if the script generate the / to the front of the script url, then everything will be fine.

Thanks

**Comment by AntoineMary** [comment]
Hi,
Nearly 5 months that I haven't touch this project... I take your request.
Soon I will have more time to work on my projects, I think I will rewrite it from scratch to handle more case.
But for the moment consider it like unmaintained.

**Comment by noXi89** [comment]
For HTML5-mode you could try to set the <base> tag in your index.html to your project root on the server. At the other hand a prefix property would be great.

**Comment by AntoineMary** [comment]
As suggested by @noXi89 , I have added a 'prefix' option, available in 1.3.1
